- name: Returns DB
  type: mysql
  info: a SQL database about portfolio and asset returns
  host: localhost
  port: 3306
  user: root
  pwd: 123_Phoenix
  db: dbllm

- name: Store DB
  type: mysql
  info: a SQL database about store tables
  host: localhost
  port: 3306
  user: root
  pwd: 123_Phoenix
  db: storedb